services:
  - type: web
    name: marketbas
    env: php
    repo: https://github.com/luispoicon1/marketbas
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://marketbas.onrender.com
